name: famka_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0' # Oder '>=3.4.0 <3.5.0' wenn du sehr präzise sein willst

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.2.1
  sf_symbols: ^0.2.0
  flutter_svg: ^2.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  sticky_headers: ^0.3.0+2
  intl: ^0.20.2
  collection: ^1.18.0
  uuid: ^4.0.0
  create_date_picker: ^1.0.0

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.0.0

  shared_preferences: ^2.0.0
  device_preview: ^1.1.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  path_provider: ^2.1.3
  flutter_image_compress: ^2.2.0 
  reorderable_grid_view: ^2.2.4
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/details/
    - assets/grafiken/
    - assets/hintergruende/
    - assets/fotos/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Compact-Text-Regular.otf

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Compact-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Compact-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Compact-Display-Regular.otf

    - family: SFProDisplayHeavy
      fonts:
        - asset: assets/fonts/SF-Compact-Display-Heavy.otf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/grafiken/famka-icon2.png"
  remove_alpha_ios: true
  # adaptive_icon_foreground: "assets/grafiken/famka-icon2.png"
  adaptive_icon_background: '#FFFFFF'

flutter_native_splash:
 # color: '#FFFFFF'
  background_image: "assets/grafiken/famka-icon2.png"
  android: true
  ios: true
  android_12:
    image: assets/grafiken/famka-icon2.png
    icon_background_color: "#FFFFFF"
    color: "#FFFFFF"