import 'package:flutter/material.dart';

enum ItemType { emoji, icon, image, addPhoto }

class GalleryItem {
  final ItemType type;
  final String? imageUrl;
  final IconData? iconData;
  final String? emoji;
  final String content;

  const GalleryItem({
    required this.type,
    this.imageUrl,
    this.iconData,
    this.emoji,
    required this.content,
  });
}

class GalleryData {
  static const List<GalleryItem> fixedThumbnails = [];

  static List<GalleryItem> getDynamicImagesGalleryItems() {
    final imagePaths = [
      'assets/grafiken/famka-kreis.png',
    ];

    return List.generate(
      imagePaths.length,
      (index) {
        return GalleryItem(
          type: ItemType.image,
          imageUrl: imagePaths[index],
          content: 'image:${imagePaths[index]}',
        );
      },
    );
  }

/*
  static List<GalleryItem> getDynamicIconsGalleryItems() {
    final icons = [
      Icons.sports_basketball,
      Icons.sports_tennis,
      Icons.directions_bike,
      Icons.snowboarding,
      Icons.directions_run,
      Icons.pool,
      Icons.fitness_center,
      Icons.sports_soccer,
      Icons.sports_handball,
      Icons.kitesurfing,
      Icons.paragliding,
      Icons.sports_mma,
      Icons.account_balance,
      Icons.alarm,
      Icons.attach_money,
      Icons.beach_access,
      Icons.bed,
      Icons.book,
      Icons.build,
      Icons.business,
      Icons.camera_alt,
      Icons.car_rental,
      Icons.celebration,
      Icons.child_friendly,
      Icons.cloud,
      Icons.computer,
      Icons.cookie,
      Icons.coronavirus,
      Icons.credit_card,
      Icons.deck,
      Icons.directions_bus,
      Icons.dinner_dining,
      Icons.diversity_3,
      Icons.drive_eta,
      Icons.edit,
      Icons.emoji_events,
      Icons.escalator_warning,
      Icons.favorite,
      Icons.feedback,
      Icons.flight,
      Icons.folder,
      Icons.forest,
      Icons.group,
      Icons.gavel,
      Icons.handyman,
      Icons.healing,
      Icons.headphones,
      Icons.help,
      Icons.home_work,
      Icons.hot_tub,
      Icons.icecream,
      Icons.keyboard,
      Icons.local_cafe,
      Icons.local_dining,
      Icons.local_florist,
      Icons.local_hospital,
      Icons.local_laundry_service,
      Icons.local_library,
      Icons.local_mall,
      Icons.local_movies,
      Icons.local_parking,
      Icons.local_pharmacy,
      Icons.local_pizza,
      Icons.local_post_office,
      Icons.local_shipping,
      Icons.location_on,
      Icons.lock,
      Icons.mail,
      Icons.map,
      Icons.medical_services,
      Icons.menu_book,
      Icons.mic,
      Icons.military_tech,
      Icons.monetization_on,
      Icons.money,
      Icons.more_horiz,
      Icons.motorcycle,
      Icons.movie,
      Icons.museum,
      Icons.music_note,
      Icons.nature,
      Icons.nightlight_round,
      Icons.no_food,
      Icons.park,
      Icons.pets,
      Icons.phone,
      Icons.photo_camera,
      Icons.pie_chart,
      Icons.place,
      Icons.play_arrow,
      Icons.psychology,
      Icons.public,
      Icons.qr_code,
      Icons.receipt,
      Icons.restaurant,
      Icons.school,
      Icons.science,
      Icons.security,
      Icons.self_improvement,
      Icons.send,
      Icons.settings,
      Icons.shopping_bag,
      Icons.show_chart,
      Icons.spa,
      Icons.stars,
      Icons.store,
      Icons.subway,
      Icons.supervised_user_circle,
      Icons.support,
      Icons.tag,
      Icons.taxi_alert,
      Icons.thumb_up,
      Icons.timeline,
      Icons.toys,
      Icons.traffic,
      Icons.train,
      Icons.tram,
      Icons.translate,
      Icons.trending_up,
      Icons.umbrella,
      Icons.vaccines,
      Icons.verified,
      Icons.video_call,
      Icons.volume_up,
      Icons.wallet,
      Icons.water,
      Icons.weekend,
      Icons.wifi,
      Icons.work,
      Icons.wine_bar,
      Icons.yard,
      Icons.zoom_in,
      Icons.zoom_out,
    ];
    return List.generate(
      icons.length,
      (index) {
        return GalleryItem(
          type: ItemType.icon,
          iconData: icons[index],
          content: 'icon:${icons[index].codePoint.toString()}',
        );
      },
    );
  }
*/

  static List<GalleryItem> getDynamicEmojisGalleryItems() {
    final emojis = [
      '⚽️',
      '🏀',
      '🎾',
      '🏸',
      '🥎',
      '🏐',
      '🏓',
      '⛷️',
      '🚴',
      '🏃‍♂️',
      '🤾‍♀️',
      '🏇',
      '🏂',
      '🏌️‍♂️',
      '🤸‍♂️',
      '🧘‍♀️',
      '🛹',
      '🛼',
      '🎿',
      '🤼‍♂️',
      '🤽‍♂️',
      '🪂',
      '🤺',
      '🧗‍♀️',
      '🏄‍♂️',
      '🚣‍♀️',
      '🚵‍♂️',
      '🏊‍♂️',
      '🏹',
      '🛷',
      '🧊',
      '🚤',
      '🪁',
      '🥋',
      '⛳️',
      '🛶',
      '🪃',
      '🏋️‍♂️',
      '🏉',
      '🥌',
      '🎉',
      '🎂',
      '🎁',
      '🎈',
      '🎊',
      '🎀',
      '🪄',
      '💖',
      '⭐',
      '✨',
      '🍎',
      '🍊',
      '🍋',
      '🍉',
      '🍇',
      '🍓',
      '🍒',
      '🍑',
      '🍍',
      '🥝',
      '🍕',
      '🍔',
      '🍟',
      '🍣',
      '🍜',
      '🍝',
      '🌮',
      '🍳',
      '🍩',
      '🍪',
      '☕',
      '🍵',
      '🥂',
      '🍻',
      '🥛',
      '🥤',
      '🍦',
      '🍫',
      '🍬',
      '🍭',
      '🏠',
      '🏢',
      '🏫',
      '🏥',
      '🏦',
      '🏪',
      '🏭',
      '🏛️',
      '🏰',
      '💒',
      '🚗',
      '🚕',
      '🚌',
      '🚃',
      '🚄',
      '🚂',
      '🚀',
      '✈️',
      '🚢',
      '⚓',
      '🐶',
      '🐱',
      '🐭',
      '🐹',
      '🐰',
      '🐻',
      '🐼',
      '🐨',
      '🐯',
      '🦁',
      '🌻',
      '🌹',
      '🌷',
      '🌸',
      '🌼',
      '🌳',
      '🌲',
      '🌴',
      '🌵',
      '🌾',
      '☀️',
      '☁️',
      '🌧️',
      '⛈️',
      '❄️',
      '🌈',
      '⚡',
      '🌬️',
      '🍂',
      '🍁',
      '📚',
      '📝',
      '📊',
      '📈',
      '📉',
      '⏰',
      '📆',
      '🗓️',
      '📍',
      '💡',
      '🎵',
      '🎶',
      '🎤',
      '🎧',
      '🎸',
      '🥁',
      '🎹',
      '🎷',
      '🎺',
      '🎻',
      '💻',
      '📱',
      '⌨️',
      '🖱️',
      '🖨️',
      '💾',
      '💿',
      '📞',
      '🔋',
      '🔌',
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🤎',
      '🖤',
      '🤍',
      '💔',
      '😀',
      '😂',
      '😅',
      '😊',
      '😇',
      '🥰',
      '😍',
      '🤩',
      '😘',
      '😗',
      '🤫',
      '🤔',
      '🤗',
      '😬',
      '😮',
      '😴',
      '😷',
      '🤒',
      '🤕',
      '🤮',
    ];
    return List.generate(
      emojis.length,
      (index) {
        return GalleryItem(
          type: ItemType.emoji,
          emoji: emojis[index],
          content: 'emoji:${emojis[index]}',
        );
      },
    );
  }
}
